plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
  id 'org.jetbrains.kotlin.plugin.compose'
}

group = 'expo.modules.sessionwidget'
version = '0.1.0'

android {
  namespace "expo.modules.sessionwidget"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
  buildFeatures {
    compose true
  }
  composeOptions {
    kotlinCompilerExtensionVersion = "1.5.1"
  }
}

dependencies {
  implementation 'androidx.glance:glance-appwidget:1.1.0'
  implementation 'androidx.glance:glance-material3:1.1.0'
}
